---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-finder
  namespace: artemis

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-finder
  namespace: artemis
rules:
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-finder
  namespace: artemis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-finder
subjects:
- kind: ServiceAccount
  name: pod-finder
  namespace: artemis
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pod-finder
  namespace: artemis
  labels:
    app.kubernetes.io/name: pod-finder
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: pod-finder
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pod-finder
    spec:
      containers:
      - name: pod-finder
        image: balchu/pod-finder
        command: ["/pod-finder"]
        args: ["check", "--namespace","artemis", "--label", "app=activemq-artemis", "--period" , "5", "--output", "/data/output.json"]
        volumeMounts:
        - mountPath: /data
          name: data-volume
        imagePullPolicy: IfNotPresent
      volumes:
      - name: data-volume
        emptyDir: 
          medium: Memory
      serviceAccountName: pod-finder
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst